## Pandas

In [2]:
#%pip install pandas numpy
import pandas as pd # mindenki pd ként roviditi
print('Hello Pandas!')

Hello Pandas!

### Feladat:
- adott egy használt autók adatainak adatbázisa, **CSV** file-ként (Car details v3.csv)
- az összefüggést szeretnénk megállapítani az adatok között:
    - hogyan hatnak a paraméterek, **független változók** (feature), pl. *km driven*, *hanyadik tulajdonos*, stb. a cél, **függő** (target) változóra: **selling price**
- most még azonban csak az adatok előfeldogozását végezzük:
    - csak **numerikus** értékekkel tudunk számolni, ezért szükség esetén konvertálni kell az adatokat
    - **hiányzó adatok** lehetnek, ezekkel kezdeni kell valamit 
    - a **target** változó és releváns input feature-ök kiválasztása

## DataFrame létrehozása, beolvasása, mentése

In [4]:
import numpy as np 

# általunk létrehozott adatokból (python lista, dictionary, numpy ndarray)
df = pd.DataFrame([["a", 1], ["b", 2]]) # 'pandas.core.frame.DataFrame', 2x2, oszlopok:'0', '1'
df = pd.DataFrame([["a", 1], ["b", 2]], columns=["Name", "Value"]) # adott oszlopnevekkel
df = pd.DataFrame({"Name": ["a", "b"], "Value": [1, 2]}) # dictionary-ből
df = pd.DataFrame({ "x1": np.arange(1, 3), "x2": np.arange(3, 5)}) # numpy ndarray-ból

# betöltés file-ból (egy sorban be lehet olvasni)
df = pd.read_csv("Car details v3.csv") # CSV-ből
# df = pd.read_csv("Car details v3.csv", sep="\t") # tab-separated values (TSV)
# df = pd.read_excel("data.xlsx") # Excel file-ból
# df = pd.read_json("file.json") # JSON file-ból

#column_names = [ "age", "cp" ] # ... 
#df = pd.read_csv("Car details v3.csv", names=column_names) # ha a CSV csak adatokat tartalmaz, oszlopnevek

# mentés file-ba
# df.to_csv('modified.csv') # df. !
# df.to_csv('modified.csv', index=False, sep='\t') # TSV
# df.to_excel('modified.xlsx', index=False)
# df.to_json("modified.json")

# numpy array-ba
# import numpy as np
# A = df.to_numpy() # ndarray-ba

df.head(2)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0

In [9]:
import pandas as pd

df = pd.read_csv("ionosphere.data", header=None) # nincsenek oszlopnevek a file-ban
df.head

# column_names = [ "column_0", "column_1", ... "column_34" ] # ... 
#df = pd.read_csv("ionosphere.data", names=column_names)

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

## Meta-adatok

In [5]:
df.head() # első 5 sor, df.head(10) első 10
df.tail() # utolsó 5
df[10:13] # első 11.-12. sor (index 0..)

print('Shape:', df.shape) # (8128, 13), rows=df.shape[0]
df.info() # type (int64, float64), non-nulls

# cols = list(df.columns.values) # cols=['name','year',...], copy-paste ha kéne
# print('Cols:', cols)

# statisztika numerikus oszlopokon (float, int, bool)
print( "min:", df['selling_price'].min() )
print( "max:", df['selling_price'].max() )
print( "avg:", df['selling_price'].mean() ) # a nem-null értékek átlaga
# print( "avg:?", df['selling_price'].sum() / df.shape[0] ) # vigyázat: ha vannak null értékek, ez != mean 
print( "dev:", df['selling_price'].std() ) # standard deviation

Shape: (8128, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB
min: 29999
max: 10000000
avg: 638271.8077017716
avg:? 638271.8077017716
dev: 806253.4035082317

## Lekérdezések, rendezés (SQL)

In [6]:
df['name'] # egy oszlop (SQL SELECT)
df[ ['name', 'year'] ] # name és year oszlopok
df[ ['name', 'year'] ][0:3] # name és year oszlopok első 3 sor

df[ df['year'] >= 2017 ] # (SQL WHERE)
# mask = df['year'] >= 2020 # egy boolean oszlop: True, ha a mezőre igaz a feltétel
# df[mask] # sorok, melyeknél a mask True értékű

df[ (df['year'] >= 2020) & (df['fuel']=='Petrol') ] # zárójelek!, binary & (SQL WHERE AND)
df[ df['name'].str.contains('Honda') ] # .str (SQL LIKE %string%)

df.sort_values('year')
df.sort_values(['year','km_driven'], ascending=[False, True]) # másodlagos rendezés

df2 = df[ ['name', 'year'] ] # új dataframe!

## Oszlop értékek, típusok módosítása

In [7]:
# df oszlop aritmetika
df['selling_price'] = df['selling_price'] / 10 # cents->dollar

# apply (lamda)
df['selling_price'] = df['selling_price'].apply(lambda x: x * 0.9)  
df['transmission'] = df['transmission'].apply(lambda x: 1 if x == 'Atomatic' else 0) 

# str.
df['max_power'] = df['max_power'].str.replace("bhp", "").str.strip()  
df['max_power'] = df['max_power'].apply(lambda x: x if x != '' else '0')

# df = df.replace("?", pd.NA) # minden ?-el jelölt adat ki-nullozása az egész táblában

# astype
df['max_power'] = df['max_power'].astype(float) # csak ha parse-olható
# df['engine'] = df['engine'].astype(int)

# map
mapping = {
    'Individual': 0,
    'Dealer': 1,
    'Trustmark Dealer': 2
}
df['seller_type'] = df['seller_type'].map(mapping)

---

## Függő (target) változó, független változók szétválasztása, feldolgozása

In [8]:
df = pd.read_csv("Car details v3.csv") # CSV-ből
y = df['selling_price'] # target
X = df.drop(columns='selling_price') # visszatérési érték a selling_price nélküli dataframe! (inplace=True)
# X sorai az input feature-ök, többdimenziós az input most; y egydimenziós

## Érdektelen oszlopok, sorok eldobása

In [39]:
X = X.drop(columns=['name', 'torque']) 
# ha a name csak a gyártó lenne (BMW, Suzuki, ...), nem biztos, hogy el kéne dobni
# torque-ot (nyomaték) azért dobjuk el, mert elég a max_power (lóerő); redundáns?

X = X.drop_duplicates() # nem hasznosak számunkra
X = X.dropna(how='all') # csupa null sorok eldobása

## Üres cellák, null (None, NaN) értékek kezelése

In [9]:
X.isna()[119:121] # True/False mátrix, maszk, True, ha null

X.isna().sum() # hány null van az egyes oszlopokban (True=1-ek összege, False=0)
# year            0
# ...
# mileage         191
# engine          191
# max_power       188
# seats           191


# df = pd.read_csv("processed.cleveland.data.csv", na_values="?") # ?-es cellák null-ként töltődnek fel már beolvasáskor

# X[X['engine'].isna()] # sorok kiiratása, amelyek null-ok adott oszlopban

name              0
year              0
km_driven         0
fuel              0
seller_type       0
transmission      0
owner             0
mileage         221
engine          221
max_power       215
torque          222
seats           221
dtype: int64

## Opciók null adatok kezelésére

In [41]:
# (0)
# X = X.dropna() # sorok eldobása, ha bármely mező null (None/NaN) => esetleg túl sok adatot eldobhatunk!

# (1) törlés, ha egy adott cella null
X = X.dropna(subset='engine') # sorok eldobása, ha az adott cella null az adott oszolpban

# (2) konstans (0, 1, -1, egyéb?)
X['seats'] = X['seats'].fillna(5) # outlier-eket vezethetünk be, "elhúzhatja" az adatokat

# (3) valamilyen számított érték
df['km_driven'] = df['km_driven'].fillna(df['km_driven'].mean()) # null érték helyettesítése átlaggal (ha numerikus)

# X.info()
 # 8   mileage        7907 non-null   object 
 # 9   engine         7907 non-null   object 
 # 10  max_power      7913 non-null   object 
 # 12  seats          7907 non-null   float64

X['seats'] = X['seats'].fillna(X['seats'].mean())
X = X.dropna(subset=['mileage', 'engine', 'max_power']) # eldobjuk a sorokat, ahol ezek null-ok

X.isna().sum() # most már nincs üres (null) adat egyik oszolopban sem

year            0
km_driven       0
fuel            0
seller_type     0
transmission    0
owner           0
mileage         0
engine          0
max_power       0
seats           0
dtype: int64

## Nem numerikus adatok átalakítása numerikussá

### Mértékegységek, szövegként tartalmazott számértékek

In [43]:
X.info() # object-ek nem jók
 # 2   fuel          6232 non-null   object 
 # 3   seller_type   6232 non-null   object 
 # 4   transmission  6232 non-null   object 
 # 5   owner         6232 non-null   object 
 # 6   mileage       6232 non-null   object 
 # 7   engine        6232 non-null   object 
 # 8   max_power     6232 non-null   object 

# 7 engine, "1248 CC"
X['engine'] = X['engine'].str.replace("CC", "") # str. !
X['engine'] = X['engine'].astype(int)

# 8 max_power, "74 bhp", "103.52 bhp", " bhp"!
X['max_power'] = X['max_power'].str.replace(" bhp", "").str.strip() # .str.strip()
# :((( " bhp" -> "", ezt nem lehet float-ba parse-olni, ez gyakorlatilag null (de nem), törölni kéne
X['max_power'] = X['max_power'].apply(lambda x: x if x != '' else None) # kinullozzuk, aztán töröljük a sort
X = X.dropna(subset='max_power')
X['max_power'] = X['max_power'].astype(float)

# 6 mileage, "23.4 kmpl", "17.3 km/kg"
X['mileage'] = X['mileage'].str.replace("kmpl", "") # str.
X['mileage'] = X['mileage'].str.replace("km/kg", "") # str.
X['mileage'] = X['mileage'].astype(float)

# TODO házi feladat: US magasság->cm? pl. 5’9" = 5* 12*2.54 (cm) + 9* 2.54 (cm) = 175

<class 'pandas.core.frame.DataFrame'>
Index: 6232 entries, 0 to 8125
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          6232 non-null   int64
 1   km_driven     6232 non-null   int64
 2   fuel          6232 non-null   object
 3   seller_type   6232 non-null   object
 4   transmission  6232 non-null   object
 5   owner         6232 non-null   object
 6   mileage       6232 non-null   object
 7   engine        6232 non-null   object
 8   max_power     6232 non-null   object
 9   seats         6232 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 535.6+ KB


### Enumerációk

In [44]:
X['fuel'].unique()

# 4 transmission, "Manual", "Automatic" 
# enum, kétértékű => lehet 0, 1
X['transmission'].unique() # ['Manual', 'Automatic']
X['transmission'] = X['transmission'].apply(lambda x: 1 if x == 'Automatic' else 0) # ternary operátor (? :)

# 3 seller_type 
# enum, de a harmadik érték nem érdekes
df['seller_type'].unique() # ['Individual', 'Dealer', 'Trustmark Dealer']
mapping = {
    'Individual': 0,
    'Dealer': 1,
    'Trustmark Dealer': 1
}
X['seller_type'] = X['seller_type'].map(mapping)

# 5 owner
# enum, de számokkal jól reprezentálható
X['owner'].unique() # ['First Owner', 'Second Owner', 'Third Owner', 'Fourth & Above Owner', 'Test Drive Car']
mapping = {
    'First Owner': 1,
    'Second Owner': 2,
    'Third Owner': 3,
    'Fourth & Above Owner': 4,
    'Test Drive Car': 0
}
X['owner'] = X['owner'].map(mapping)

### Enumerációk, amelyek számként nem jól reprezentálhatók

In [45]:
# 2 fuel????
X['fuel'].unique() # ['Diesel', 'Petrol', 'LPG', 'CNG']

# számokkal nem jól reprezentálható -> "dummies"
X = pd.get_dummies(X, columns=['fuel']) # fuel oszlop helyett 4, 1-hot encoding

X.head(3)
# fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  
# False     True         False     False

,year,km_driven,seller_type,transmission,owner,mileage,engine,max_power,seats,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,2014,145500,0,0,1,23.40,1248,74.00,5.0,False,True,False,False
1,2014,120000,0,0,2,21.14,1498,103.52,5.0,False,True,False,False
2,2006,140000,0,0,3,17.70,1497,78.00,5.0,False,False,False,True

In [46]:
# kész vagyunk, minden int, float vagy bool
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6231 entries, 0 to 8125
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          6231 non-null   int64
 1   km_driven     6231 non-null   int64
 2   seller_type   6231 non-null   int64
 3   transmission  6231 non-null   int64
 4   owner         6231 non-null   int64
 5   mileage       6231 non-null   float64
 6   engine        6231 non-null   int64
 7   max_power     6231 non-null   float64
 8   seats         6231 non-null   float64
 9   fuel_CNG      6231 non-null   bool
 10  fuel_Diesel   6231 non-null   bool
 11  fuel_LPG      6231 non-null   bool
 12  fuel_Petrol   6231 non-null   bool
dtypes: bool(4), float64(3), int64(6)
memory usage: 511.1 KB

## Egyéb: új oszlopok hozzáadása

In [47]:
X['oszlop'] = 1 # új oszlop, csupa 1-es, df-et módosítja!

X['discounted'] = df['selling_price'].apply(lambda x: x * 0.9) # új oszlop, apply 

X['km_per_year'] = X['km_driven'] / (2025 - df['year']) # új oszlop, évi futás

X.head(2)

# oszlopok törlése
# X.drop(columns=['oszlop', 'discounted', 'km_per_year'], inplace=True) # oszlop(ok) törlése

,year,km_driven,seller_type,transmission,owner,mileage,engine,max_power,seats,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,oszlop,discounted,km_per_year
0,2014,145500,0,0,1,23.40,1248,74.00,5.0,False,True,False,False,1,405000.0,13227.272727
1,2014,120000,0,0,2,21.14,1498,103.52,5.0,False,True,False,False,1,333000.0,10909.090909

## ...egyéb: join, stack, ...

In [48]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [30, 40]})
df2 = pd.DataFrame({'Name': ['Cecil'],        'Age': [50],     'Salary': [10000]})
pd.concat( [df1, df2], ignore_index=True) # VStack, df1 sorai után df2 sorai (NaN-ok)

df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [30, 40]})
df2 = pd.DataFrame({'Salary': [5000, 7000]})
pd.concat( [df1, df2], axis=1) # HStack, df1 oszlopai, utána df2 oszlopai, hstack, index szerint

df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [30, 40]})
df2 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Salary': [5000, 7000]})
pd.merge(df1, df2, on='Name') # inner join Col1 azonos értékei szerint, metszet

df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [30, 40]})
df2 = pd.DataFrame({'Name': ['Alice', 'Cecil'], 'Salary': [5000, 10000]})
pd.merge(df1, df2, on='Name', how='outer')  # outer join, union

df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Cecil'], 'Position': ['boss', 'worker', 'boss'], 'Salary': [5000, 7000, 10000]})
df.groupby(['Position']).count() # azonos értékű Col sorok összevonása, többi megszámolása (nem null-ok)
df.groupby(['Position'])['Salary'].mean()

Position
boss      7500.0
worker    7000.0
Name: Salary, dtype: float64

## Feladat: DONE
- adott egy használt autók adatainak adatbázisa, **CSV** file-ként (Car details v3.csv)
- az összefüggést szeretnénk megállapítani, hogyan hatnak a paraméterek (független változók, feature-ök, pl. km driven, hanyadik tulajdonos) és **cél** (függő, target) változóra: **selling price**
- most még azonban csak az adatok előfeldogozását végezzük:
    - a target változó és releváns input feature-ök kiválasztása 
    - csak *numerikus* értékekkel tudunk számolni, konvertálni kell az adatokat
    - *hiányzó adatok* lehetnek, ezekkel kezdeni kell valamit